spring:
  application:
    name: ms-gerenciamento-sessoes

  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html