CREATE TABLE SESSOES (
    id INT(10) AUTO_INCREMENT PRIMARY KEY,
    id_filme INT(10) NOT NULL,
    preco DECIMAL(10, 2) NOT NULL,
    data_hora DATETIME NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;