CREATE TABLE filmes(
    id INT(10) AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    duracao INT(3) NOT NULL,
    genero VARCHAR(50) NOT NULL,
    autor VARCHAR(100) NOT NULL,
    data_lancamento DATE NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4