server:
  port: 8085
management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    base-url: ${SPRING_ZIPKIN_BASE_URL:http://zipkin:9411}
    tracing:
      endpoint: ${SPRING_ZIPKIN_BASE_URL:http://zipkin:9411}/api/v2/spans
spring:
  application:
    name: ms-api-gateway
  cloud:
    gateway:
      routes:
        # Rotas para Swagger API Docs (order menor = maior prioridade)
        - id: autenticacao-health
          uri: lb://ms-autenticacao-cinema
          order: -2
          predicates:
            - Path=/auth/health
          filters:
            - RewritePath=/auth/health, /actuator/health
            - RemoveRequestHeader=Authorization

        - id: autenticacao-docs
          uri: lb://ms-autenticacao-cinema
          order: -1
          predicates:
            - Path=/auth/v3/api-docs
          filters:
            - RewritePath=/auth/v3/api-docs, /v3/api-docs
            - RemoveRequestHeader=Authorization

        - id: catalogo-health
          uri: lb://ms-gerenciamento-catalogo
          order: -2
          predicates:
            - Path=/catalogo/health
          filters:
            - RewritePath=/catalogo/health, /actuator/health
            - RemoveRequestHeader=Authorization

        - id: catalogo-docs
          uri: lb://ms-gerenciamento-catalogo
          order: -1
          predicates:
            - Path=/filmes/v3/api-docs
          filters:
            - RewritePath=/filmes/v3/api-docs, /v3/api-docs
            - RemoveRequestHeader=Authorization

        - id: clientes-docs
          uri: lb://ms-gerenciamento-clientes
          order: -1
          predicates:
            - Path=/clientes/v3/api-docs
          filters:
            - RewritePath=/clientes/v3/api-docs, /v3/api-docs
            - RemoveRequestHeader=Authorization

        - id: clientes-health
          uri: lb://ms-gerenciamento-clientes
          order: -2
          predicates:
            - Path=/clientes/health
          filters:
            - RewritePath=/clientes/health, /actuator/health
            - RemoveRequestHeader=Authorization

        - id: sessoes-docs
          uri: lb://ms-gerenciamento-sessoes
          order: -1
          predicates:
            - Path=/sessoes/v3/api-docs
          filters:
            - RewritePath=/sessoes/v3/api-docs, /v3/api-docs
            - RemoveRequestHeader=Authorization

        - id: sessoes-health
          uri: lb://ms-gerenciamento-sessoes
          order: -2
          predicates:
            - Path=/sessoes/health
          filters:
            - RewritePath=/sessoes/health, /actuator/health
            - RemoveRequestHeader=Authorization

        # Rotas de API
        - id: autenticacao
          uri: lb://ms-autenticacao-cinema
          order: 0
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth(?<segment>.*), /v1/auth${segment}

        - id: catalogo
          uri: lb://ms-gerenciamento-catalogo
          order: 0
          predicates:
            - Path=/filmes/**
          filters:
            - RewritePath=/filmes(?<segment>.*), /v1/filmes${segment}

        - id: clientes
          uri: lb://ms-gerenciamento-clientes
          order: 0
          predicates:
            - Path=/clientes/**
          filters:
            - RewritePath=/clientes(?<segment>.*), /v1/clientes${segment}

        - id: sessoes
          uri: lb://ms-gerenciamento-sessoes
          order: 0
          predicates:
            - Path=/sessoes/**,/reservas/**
          filters:
            - RewritePath=/sessoes(?<segment>.*), /v1/sessoes${segment}
            - RewritePath=/reservas(?<segment>.*), /v1/reservas${segment}


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    urls:
      - name: Autenticação API
        url: /auth/v3/api-docs
      - name: Catálogo API
        url: /filmes/v3/api-docs
      - name: Clientes API
        url: /clientes/v3/api-docs
      - name: Sessões API
        url: /sessoes/v3/api-docs
    urls-primary-name: Autenticação API
  api-docs:
    enabled: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true