server:
  port: 8888
spring:
  application:
    name: config-server-app
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Pedro-Henrique-Dias-Romanowski/config-server-cinema.git
          default-label: main
          search-paths:
            - "{application}"
          clone-on-start: true
