cliente.email.existente = O email informado já existe, por favor utilize outro.
cliente.objeto.nulo = Todos os dados do cliente são obrigatórios.
cliente.senha.invalida = A senha deve conter entre 5 e 15 caracteres.
cliente.lista.vazia = Nenhum cliente encontrado.
cliente.inexistente = Cliente não encontrado.
reserva.nao.encontrada = Reserva não encontrada.
reserva.inativa = A reserva está inativa.
cliente.saldo.insuficiente = Saldo insuficiente.
mensagem.boasvindas.cinema.email = Seja bem vindo ao cinema, %s! Aproveite nossos filmes e sessões.
mensagem.exclusao.cinema.email = É uma pena que você está nos deixando, %s! Você pode voltar a qualquer momento.
ms.sessoes-reservas.indisponivel = Serviço de sessões e reservas indisponível, tente novamente mais tarde.