name: notification.yml
on:
    push:
        branches:
        - main
jobs:
    notify:
        runs-on: ubuntu-latest
        steps:
          - name: Run Discord Webhook
            uses: johnnyhuy/actions-discord-git-webhook@main
            with:
              webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
